### ISSUE TITLE
As a student I can view the result of my quiz

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#16]
- One off page that shows total score once the quiz has ended
- animations for receiving medals and trophies.
- Ability to navigate back to dashboard

**Comment by minaorangina** [comment]
Hi @stianr, need a quick memory refresh on this one.  I remember us discussing that scores should be a percentage in some cases, rather than the actual number.  I assume a student should see the actual number of correct answers they got just after the quiz has completed.

Was it the module leaderboard and students' tailored feedback where we should use percentage scores instead?  And generally speaking, where would you like us to use/display percentages versus the actual number of correct answers?

**Comment by stianr** [comment]
Hi Mina,

I think the only places we needed to calculate percentages were for the trophies. For the individual feedback score and leaderboard, scores should be the number of questions the student has answered correctly - either in that quiz (for the feedback) or across all the quizzes so far (for the leaderboard).

Stian.

________________________________

**Comment by minaorangina** [comment]
@stianr Ok, thanks for clearing that up
