### ISSUE TITLE
Potential DB architecture

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#20]
To view the structure please visit - http://ondras.zarovi.cz/sql/demo/

Then click Save/Load button and paste the following: 
##### Screenshot V1

![screen shot 2016-07-05 at 17 45 06](https://cloud.githubusercontent.com/assets/2305591/16592373/4b20d53e-42d8-11e6-9079-d7eae0e09003.png)
##### Screenshot V2

![screen shot 2016-07-06 at 18 06 16](https://cloud.githubusercontent.com/assets/8915092/16627279/6f8deb88-43a4-11e6-96b6-716baef20ddd.png)

**Comment by minaorangina** [comment]
### Version 3
![screen shot 2016-08-20 at 15 36 31](https://cloud.githubusercontent.com/assets/8915092/17831832/fecc6c88-66eb-11e6-8e6f-4d40285d2774.png)

**Comment by minaorangina** [comment]
### Version 4
Updates the trophy names
![screen shot 2016-08-23 at 12 10 36](https://cloud.githubusercontent.com/assets/8915092/17889964/d21d13fe-692a-11e6-88c1-56915fcfaf9b.png)

**Comment by sohilpandya** [comment]
Updated the `users` table to:
<img width="171" alt="screen shot 2016-12-16 at 14 55 05" src="https://cloud.githubusercontent.com/assets/2305591/21266863/c9ec00da-c39f-11e6-9813-95735cc2a1ad.png">

**Comment by franzmoro** [comment]
updates to db architecture from implementing surveys:
- **correct_answer** in *questions* table now **optional** (was mandatory)
- new **surveys** table with fields:
  - *survey_id*
  - *module_id*
  - *name*
  - *is_presented*
- **responses** table:
  - **quiz_id** now **optional** (was mandatory)
  - new **survey_id** field, **optional**

**Note**: the *quizzes* table in V4 needs to reflect the *is_last_quiz* field too (not due to the above changes).

**Comment by iteles** [comment]
Closing this technical issue, no longer relevant 👍
