### ISSUE TITLE
Student receives email to confirm they have signed up

### ISSUE THREAD

**Issue by iteles** [cul-2016/quiz#249]
As a student,
I would like to receive an email to confirm I have signed up with the application
So that I always know which email address I have used.

<hr/>
*Notes:*
The potential of adding full email verification for the students (like we will have for lecturers #248 ) was discussed, but ultimately discarded as an idea to ensure maximum reduction of friction upon sign up, particularly because students will often be signing up in the class, ahead of the quiz and may not have access to their emails straight away.

**Comment by sohilpandya** [comment]
@stianr 
For now, we set up the following welcome email for students:

```
Hi **username**!

Thank you for registering as a student!
You can access your account via http://cul-app.herokuapp.com/

City University Quiz app http://cul-app.herokuapp.com/

```

Could you please let us know how you would like to modify the content of this email. 

Thanks!

**Comment by stianr** [comment]
@sohilpandya To keep it more generic could we have text as "Thank you for registering to take part in quizzes!" rather than 'registering as a student'. If we use it in staff training or CPD courses, people might not like to think of themselves as students. Could we also have something explicit (given bitter experience with some students) that says "You are registered with email address: XX@XX.XX and username: XXXX." (I know it's in the message already, but students do sometimes use multiple email accounts and message forwarding so they don't always know immediately which email address it was sent to...)

**Comment by stianr** [comment]
User story looks good.

**Comment by franzmoro** [comment]
issue ready for testing on new [staging environment](http://cul-app-staging.herokuapp.com)

**Comment by stianr** [comment]
Works well. Just needs update to 'registering as a student' text as above.

**Comment by franzmoro** [comment]
email text modified as agreed

**Comment by stianr** [comment]
Great - thanks.
