### ISSUE TITLE
Forgotten password / Password reset

### ISSUE THREAD

**Issue by iteles** [cul-2016/quiz#250]
As a user of the quiz app,
I would like to be able to see and use a 'Forgotten password' link 
So that when I forget my password I am able to create a new one and keep using the application (rather than having to create a new account and losing all of my data).

**Comment by stianr** [comment]
Looks good - presumably the user (whether lecturer or student) will enter their email address (rather than username) to reset their password and will receive and email with link to reset password. 

As a student user of the app, I would also want the option of being reminded of my username, if username is being used for login. Without this I might get stuck trying to log in. Better still, we could allow users to log in using either email-password combination (current setup) or username-password combination (planned development for this version).

**Comment by franzmoro** [comment]
issue ready for testing on new [staging environment](http://cul-app-staging.herokuapp.com)

**Comment by stianr** [comment]
Password reset works well.

**Comment by iteles** [comment]
Thanks @stianr. If you're happy that an issue has been dealt with, can you please close it so that it is archived in our backlog? ✨

**Comment by stianr** [comment]
Didn't close this as I also mentioned being reminded of username. Shall I separate that out into a new issue, and close this one?

**Comment by iteles** [comment]
Ah @stianr , please do!
