### ISSUE TITLE
Students should be able to reveal *correct* answer when reviewing questions

### ISSUE THREAD

**Issue by iteles** [cul-2016/quiz#260]
As a student who is reviewing the questions in the quiz along with the various multiple choice answers (see #259),
I would like to be able to click a button to reveal the **correct answer**,
So that I can use the quizzes as a study guide when I am revising for my exams.

_Note: This is an enhancement of #259 and will need to be time estimated before @stianr can prioritise it._

**Comment by sohilpandya** [comment]
addressed in #259

**Comment by franzmoro** [comment]
issue ready for testing on new [staging environment](http://cul-app-staging.herokuapp.com)

**Comment by iteles** [comment]
@franzmoro @sohilpandya Same login details as before for Stian?

**Comment by sohilpandya** [comment]
@iteles yes, same test login details as before.

**Comment by stianr** [comment]
Shows correct answer, but correct answer is displayed by default - aim was to allow user to press a button to show correct answer (people learn better if they try to anticipate the correct answer rather than seeing it upfront). Maybe need to estimate time for that part of the implementation - the benefit is more marginal given the enhancement that's already been made here.

**Comment by franzmoro** [comment]
button to reveal correct answer (styling awaiting for designs) ready for testing on staging environment

**Comment by stianr** [comment]
I've tried with a two-item quiz, and it all works well.

**Comment by iteles** [comment]
Oops, incorrect milestone on this!
