### ISSUE TITLE
Quizzes with questions that have no correct answers

### ISSUE THREAD

**Issue by iteles** [cul-2016/quiz#262]
As a lecturer,
I would like to have quizzes where some questions may not have a correct answer,
So that I can ask more qualitative questions, allowing students to provide their opinions and give feedback.

_Note: These should not count towards the final score and should not affect the medals and trophies._

@sohilpandya @franzmoro We discussed both individual questions as mentioned above or the possibility of having _entire quizzes_ with no correct answers and which don't count towards the scoring, medals and trophies (see #263 ). Can we please estimate both of these issues and their implications so that @stianr is able to make a decision on which of these options to go for? 
I would suggest a list of technical tasks can be contained within the comments of these issues for now (in the estimation stage) and split out into sub-issues when a decision is made.

**Comment by sohilpandya** [comment]
1. Creating a new field `is_survey` in the questions table which would determine whether the question is a survey or an actual question.
- When doing the calculations, we can discard any question that has `is_survey` set to true
  - This would mean having to combat a lot of existing queries and making sure that they don't break.
- We would put a constraint on the lecturer's side, where they must enter a question with a correct answer so that no quiz has all questions with no correct answers. (this is to avoid further complications)
**5 Days- depending on edge cases**
- I think our initial estimates were slightly lower, but we did not think of some of the edge cases that were brought up in the meeting we had with Stian and Yinka.

**Comment by stianr** [comment]
#263 is preferable approach, so this doesn't need to be taken further.
