### ISSUE TITLE
Quizzes where entire quiz has no correct answers

### ISSUE THREAD

**Issue by iteles** [cul-2016/quiz#263]
As a lecturer,
I would like to have quizzes where where there are no correct answers,
So that I can ask more qualitative questions, allowing students to provide their opinions and give feedback without it having an impact on the students' scores and trophies/medals.

@sohilpandya @franzmoro This differs from https://github.com/cul-2016/quiz/issues/262 in that this issue deals with an **entire quiz** that has no correct answers and doesn't impact the scoring, rather than individual questions.

As mentioned in #262, please estimate both of these issues so that @stianr can make a decision on which to go with.

**Comment by sohilpandya** [comment]
We've been brainstorming ideas with regards to this issue.

1. Create a separate table called surver_quiz
- All quizzes that are marked as a survey quiz will appear under this table in the db.
- We would not count these quizzes when calculating the total scores/averages etc, they would still rely on the existing quiz table
- Because of this approach, the viewing of survey quizzes will have to be separate from actual quizzes.
- It doesn't have to touch existing queries. They can remain as is. 
  **3 Days**

2. Creating the survey quiz in the same db table as quiz, but add a new field `is_survey` which would determine whether the quiz is a survey or an actual quiz
- We can keep the same UI and present these surveys in the same table as all the other quizzes
- We would have to alter all the existing queries to make sure they do not count any quizzes which have `is_survey` set to true (that is a lot of work)
**5 Days**

**Comment by stianr** [comment]
This is both better for the user and quicker than the alternative option in #262 - so is definitely preferable
