### ISSUE TITLE
Intermittent: Module overview page fails to load

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#407]
This has happened a few times - I have returned to the module overview page after completing a quiz and see this:

![image](https://cloud.githubusercontent.com/assets/16817089/22405202/d67cdaea-e636-11e6-9af2-18eac42a23fc.png)

Manually refreshing the page sometimes helps, and sometimes doesn't. If I can find any pattern in when it happens I will update this issue.

**Comment by stianr** [comment]
Getting this a lot now. Found with Android/Firefox as well as Chrome and Firefox on Windows (which is everything I've managed to test with). A manual refresh always solves the problem.

Perhaps related, when the page does load, and I click on one of the quizzes to review questions, sometimes all that happens is that the menu bar (with Home and Logout on) disappears but I remain on the same screen (see below).

![image](https://cloud.githubusercontent.com/assets/16817089/22479072/5eb75ecc-e7e4-11e6-8049-4db6c2fd190a.png)

**Comment by sohilpandya** [comment]
Hi @stianr, after doing some research it looks like the issue is being caused by us manually editing the data on the database, the issue goes away as soon as we refresh the database with fresh data. 

An error in the backend caused by it trying to fetch undefined information leads to this issue:
<img width="950" alt="screen shot 2017-02-01 at 12 16 21" src="https://cloud.githubusercontent.com/assets/2305591/22517235/6df9f8c4-e8a0-11e6-9ba9-a69cedd49496.png">

This does go away as soon as we refresh the database, This might be worth testing again once we've completly finished working and will no longer be making manual edits to the database.

**Comment by stianr** [comment]
No problems reported by students, so closing.
