### ISSUE TITLE
Sharing / reusing previous quizzes

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#484]
As a lecturer, I want to be able to use a quiz I have set up, and:

- Share it with another lecturer so that they can edit and run it with their students
- Duplicate it into another module so that I can run it on a different student group or year

There are two options we've looked at:

1. Export/import - download a file containing all the quiz information, which can be shared and uploaded to another module
2. Generate code - click on 'share quiz' to generate a code that can be entered in another user/module combination to import the quiz

On first pass we thought 2 would be easier and cleaner. If this is the case then it would need the following modifications:

- [ ] On a lecturer's module overview page, for each quiz include a 'Share quiz' button, next to the 'Preview Quiz' and 'Run Quiz' buttons. This would then give a pop-up containing the unique code plus text "This is a unique code for this quiz - you can share this with anyone who you want to have a copy. They just need to click on 'Import Quiz' and enter this code to get a copy of the quiz. They will not have access to any details about people who have taken your quiz, only a copy of the questions, options and correct answers, so they can run it themselves with their own class."

- [ ] On the same page, below all the current quizzes, have an 'Import Quiz' button, which brings up a dialog with a text field and a submit button. On pressing the submit button, the text field contents is compared against quiz identifiers. If there's no match, present text saying "No quiz found with this code". If there is a match, import quiz to current module in the same way that the add new quiz page does.

Potential issues/queries

- Security - the unique code should not be guessable 
- Sharing - there will be a gap between Lecturer 1 generating the code and Lecturer 2 entering the code to import the quiz. If the quiz is edited in the meantime, are those edits incorporated into the quiz that Lecturer 2 imports? In other words do we (a) copy for Lecturer 2 whatever is in the quiz shared by Lecturer 1 at the point at which Lecturer 2 enters the code, or (b) take a snapshot of the quiz at the point that the share code is generated so that Lecturer 2 imports that version of the quiz no matter when they do it. I imagine (a) is easier, and is fine.
- Do multiple share attempts always generate the same code? (That shouldn't be a problem if we do (a) above.)
- Do we check for multiple imports of a particular quiz? (Not sure it's necessary.) Just need to ensure that each new instance has a new ID so there's no clashes.

**Comment by sohilpandya** [comment]
**Sharing / Reusing previous quizzes**

- New share quiz button somewhere on the screen
- If a quiz has not been shared then create a share code, if a share code exists already then show that instead of generating a new one. 
- Creates a unique sharing code and set it in a new column called share. (DB Migration for new column)
- New import Quiz button where this new id can be posted in. 
- When a user enters this, it will do the following
    - Check if it exists, if not then show error
    - Create a new quiz with the same information as the previous quiz linked to that unique share code
    - Also copy all the questions that belong to the quiz and save a new copy belonging to the new quiz id and module id. etc. 
- We only make a copy of the quiz and all the questions as and when the user enters the unique id. So this means if the original lecturer has edited the quiz then its the edited quiz that will be copied over as we overwrite old quiz information when the user edits/updates a quiz. 
- With regards to clash with quiz_id, this should not be an issue as we will create a copy for the quiz and question table so that they are not related to the old user in any way. 

_This process needs to be applied to sharing surveys as well_

**Comment by sohilpandya** [comment]
@jackcarlisle it will now show the code on the right-hand side if present. 
![screen shot 2017-08-22 at 18 22 16](https://user-images.githubusercontent.com/2305591/29578784-69fc9af8-8768-11e7-8a23-8d48034adaee.png)

**Comment by sohilpandya** [comment]
@stianr could you please test this functionality on staging. 

Thanks

**Comment by stianr** [comment]
Seems to be working great!
