### ISSUE TITLE
Indicate that page is loading

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#495]
As a lecturer or student, when I arrive at a page within the webapp, sometimes initially it only shows the top menu bar (Home - Logout), and everything else is blank. This seems to be because the rest of the page is loading, and sometimes can take a few seconds. I want to know that the rest of the page is loading, rather than there is a problem with the app.

While the rest of the page is being retrieved, would it be possible to have a loading animation presented somehow, so that it is clear that something is happening?

**Comment by stianr** [comment]
This may be worth discussing - I haven't seen much of a problem with the main page body being slow to load during testing this time, so it may be that it's not a good use of limited time to do this.

**Comment by stianr** [comment]
As discussed in the meeting today, this would be good to have a time estimate for.

**Comment by sohilpandya** [comment]
@stianr It will take us a couple of hours to implement the designs that will be provided by the designers, the initial spike on this has resulted in a simple Quodl logo with the text loading that appears when we are fetching any kind of data. We will let you know once it is on Staging so that you can test it yourself but this is how it looks currently. 
![screen shot 2017-08-22 at 12 42 38](https://user-images.githubusercontent.com/2305591/29563885-6fcf7238-8737-11e7-9bba-b58703902784.png)

**Comment by stianr** [comment]
That sounds well worth doing now. (And the current graphic will do fine if the designers run out of time...)

**Comment by sohilpandya** [comment]
Hi @stianr can you please test this and let us know if it works as expected. 

Thanks.

**Comment by stianr** [comment]
This is great! Working on my Surface and S7.
