### ISSUE TITLE
Free Plan

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#621]
- [x] Create a new url for lecturers to sign up, currently, this is only accessible by Stian, we need to make this public 

- [x] Add a new column in user database table for setting a trial version. We can have an expiry time, which will be a bigint 

- [x] submit trial information to users table when saving new sign up 

- [x] Check trial_expiry_date and if users out of trial time then log user out. 

When user tries to log in:
- [x] check for the trial time
- [x] display message to upgrade account by contacting an email address or phone number.

**Comment by sohilpandya** [comment]
@stianr:
- sign up as a lecturer for a free version (same flow applies when signing up as before) 
- current expiry time is 7 days
- try sigining in with trialexpired@city.ac.uk same p/w as testing and view the error message they recieve. 

Please open an issue about adjusting the expiry time and providing a warning message when trial is about to expire.

**Comment by stianr** [comment]
This seems to work. I have signed up as a new lecturer, which has given me access (but as it looks the same as a full account, I can't verify that it's actually a trial rather than a full version, but I'm assuming it is.

So at the end of the trial, I just need to create a client account with the same email address, and that then moves them into an individual lecturer subscription. That worked for me.

That all seems to be working as it should, so I'll close this.
