### ISSUE TITLE
Lecturer Updates

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#622]
Individual: 
- [x] we should check if they have the paid field checked.
  - If they do then we let them in
  - else we need to show a message to ask them to upgrade the account to a paid plan or if they need to pay their subscription. 

Individual as part of a Group Plan:
- In the newly created lecturer sign up flow, we add a new optional field called code/secret/something…
- When the user tries to sign up, we check if the code exists and is valid, 
    - If it is valid. Need to create a new table which contains payment details including a code.
    - a limit has not been reached (i.e. whatever limit we set, it will check if those many users have already signed up), then we take the user in
    - If it is not valid, then we show a message and ask them to enter a different code or sign up for a trial.

**Comment by jessicasalmon** [comment]
When the user signs in, we need to:
- [ ] check if paid is true or false for the given user 
- [ ] if false, we display an error message asking them to get in touch with the administrator to sort out payment 
- [ ] if true, we let them in to the app

**Comment by jessicasalmon** [comment]
When a user is logged in, and super-admin changed `paid` from true to false:

- [x] delete that user session from the redis database, which will log the user out, and when they try to log in the above flow will be triggered

**Comment by jessicasalmon** [comment]
Individual lecturer as part of a group: 

- [ ] add an optional field to signup form for the code 
- [ ] send the code to the backend
- [ ] add additional field in users database called code
- [ ] In backend, check if they have a code, and if the code matches an existing code in the account_management table
- [ ] if it does, we will check that the group admin is not at the limit of their quota of users. 
- [ ] we'll need to add the ability to set a quota of users when adding a group admin
- [ ] if they pass, we sign them up with correct privilages 
- [ ] otherwise, we show a message and ask them to enter a different code or sign up for a trial. 

We need to alter the flow of user sign in, as we'll now need to check on a code for group admin.

**Comment by jessicasalmon** [comment]
Testing instructions:

**Individual Lecturer** 
* try to log in as an individual unpaid lecturer - individualunpaidlecturer@city.ac.uk
* log in as an individual paid lecturer - individualpaidlecturer@city.ac.uk
  * in an incognito tab, sign in using lecturer@city.ac.uk (super-admin)
  * click edit for individualpaidlecturer and turn paid to no
  * now, go back to your other browser window and refresh
  * you will see that you have been logged out   

**Group Lecturer**
go to 'sign up as a lecturer': 
  * test the error message, when user has entered a fake code. For this enter information in all of the fields (enter anything in the 'code' field)
    * you will see an error message that the code is incorrect
  * test the error message when the user limit has been reached
    * sign up with any details but the code must be 'limitreached'
    * you will see an error message saying that the limit of users for that group has been reached

**Comment by stianr** [comment]
Great! This all works well.
