### ISSUE TITLE
Group Admin 

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#623]
- This user will have a new area called admin (different to super admin) 
    - Where they can see all the lecturers that are using the code related to them.
    - They will also be able to delete this user. 

----------------

- set account type to be `group admin`
- If a user has paid, we should have the email address for which they paid.  
Related to #620 

**Sign Up** 
- [x] when a user signs up and the code with the email match a client account, they will be given the group admin right
- [x] In the user's table, we need to add a group_admin field (boolean) Setting it to true if the above is matched.

**Sign In**
- [x] if Group Admins client account paid turns to false, they should not be able to log in. (should be asked to contact Quodl to pay) 
- [x] They should be logged out if it turns to false

**Admin Dashboard**
- [x] fetch `is_group_admin` in reducer
- [x] if user is a group_admin, show an admin button in navbar
- [x] Fetch a list of all the lecturers using the code
~~allow them to be deleted.~~

**Comment by jessicasalmon** [comment]
Deactivate/ Activate user functionality: 

We've been working on the ability to delete the user from the group admin but after the stand up with @iteles we'll now be taking a step back and adding a functionality to deactivate/reactive a user. The flow for that is described below:

- [x] Group admin can have a look at all the users in the group
- Toggle whether a user can actively use the app
  - create a new is_user_active field or equivalent so that we can control the user. 
  - we also need to update the flow to check if the user limit has been reached when a user signs up as we also need to consider if the user is active before adding up the total users on a code. 
- If a user is disabled, we give them a message about account deactivation and to get in touch with the administrator
- They also need to be logged out if they are already logged in.

It's a slightly longer flow than just deleting a user from the app and will take some additional time. **T6h**

Will create an issue for the future as this flow does not tackle a group lecturer wanting to switch alliance to a different university or become an individual lecturer. Not in Scope.

**Comment by sohilpandya** [comment]
Hey @stianr, Details for testing this flow: 
- log in with `groupadmin@city.ac.uk`
- access admin dashboard
- disable a user
- count of active users vs limit will change. 
  - we also have a custom message which is shown if the user hits the limit. The message says `You have used all your seats, please contact Quodl to upgrade the account or deactivate some users to free up spaces`
- Admin will not be able to enable users if this limit is reached, they will have to disable a user and then enable the others. 
  - try logging in as the user (grouplecturer1@city.ac.uk if they are disabled)
  - you should get the custom error message
- enable the user back.
- in an incognito window, login as `grouplecturer1@city.ac.uk`
  - disable the user from the admin dashboard
  - refresh the incognito window, the user will be logged out and when trying to log in they'll receive the same message as above. 

This flow does not delete the user. we still keep the information changed due to conversation https://github.com/cul-2016/quiz/issues/623#issuecomment-374721226

**Comment by stianr** [comment]
The accounts bit works well. Logout when deactivated works well. I can't add more accounts as I don't have the code for this group admin.

**Comment by sohilpandya** [comment]
@stianr the code for this group admin is `groupadminsecretcode`

**Comment by stianr** [comment]
Thanks @sohilpandya - I'm in. All seems to be working well. Noting that the number of spaces taken (max 5) is larger than the number of accounts in the list - not sure why that is, but maybe it's just local to the way this was set up.

One issue is that we tell users group admins when they reach their limit that they have to upgrade, but I can't see any way we can change the number of accounts/seats that the group admin has - presumably I can do that manually by changing the total number of seats directly in the database?

**Comment by jessicasalmon** [comment]
Hey @stianr, we've made the following changes, please test:

> Noting that the number of spaces taken (max 5) is larger than the number of accounts in the list - not sure why that is, but maybe it's just local to the way this was set up.

That was because the group admin is also considered a lecturer (i.e they take up a spot). We're now displaying the group admin in the list, so the number of people in the list and number of spaces taken now match. We've removed the ability for the group_admin to disable themselves (like in super admin)

> One issue is that we tell users group admins when they reach their limit that they have to upgrade, but I can't see any way we can change the number of accounts/seats that the group admin has - presumably I can do that manually by changing the total number of seats directly in the database?

Great spot! We've added the ability to edit the number of account/seats that a group admin has.

**Comment by stianr** [comment]
Thanks @jessicasalmon. Re group admin counting the formatting goes a bit odd when the group admin is in the list. Could we revert to what we had before - we can just set it up to have one extra account per group or tell group admins what's going on.

There's a bug in the ability to edit number of seats - if as superuser you delete the text that's already in the 'number of seats' field when editing a client, the whole field disappears. If you then inadvertently save, it then impossible to change to number of seats because the field is never visible again.

**Comment by jessicasalmon** [comment]
Hey @stianr - can you have a look at this on staging and also could you let us know if you'd like us to add the text we mentioned, or keep it the same. If you're happy with it as it is currently, please close the issue.

**Comment by jessicasalmon** [comment]
> There's a bug in the ability to edit number of seats - if as superuser you delete the text that's already in the 'number of seats' field when editing a client, the whole field disappears. If you then inadvertently save, it then impossible to change to number of seats because the field is never visible again.

we fixed this bug, please check it out on staging :)

**Comment by stianr** [comment]
Much belatedly, thanks for this - all working as it should!
