### ISSUE TITLE
Set up test environment for LTI

### ISSUE THREAD

**Issue by Danwhy** [cul-2016/quiz#674]
To test the LTI integration, we'll need to deploy the current state of the app to staging, and set up the Moodle sandbox environment to integrate with Quodl.

I'll write up some documentation on how to go about doing that today.

**Comment by Danwhy** [comment]
@stianr The lti integration is live on staging now. I've written up a guide on what you need to do to set it up on Moodle here: https://github.com/cul-2016/quiz/blob/staging/LTI.md

I'll send you the required secret token in a separate email ([as mentioned here](https://github.com/cul-2016/quiz/blob/staging/LTI.md#preconfiguring-tools))

**Comment by stianr** [comment]
Hi @Danwhy, thanks for everything on this. The leaderboard is working well. But I'm struggling with the LTI demo. I had to preconfigure Quodl, but that seemed fairly straightforward. I was then able to add it to my moodle page, and it looked as I think it should:

![image](https://user-images.githubusercontent.com/16817089/42424451-6f08f512-8304-11e8-95eb-19e298ee5753.png)


But clicking on a link opens a new tab with the correct URL, but gives a 400 error across multiple browsers:

![image](https://user-images.githubusercontent.com/16817089/42424288-f020c290-8301-11e8-96dc-f23d783f970e.png)

It's possible that I've misconfigured something - maybe something I just missed because it's late at night. Alternatively, it could be that as the options and setup are slightly different for me than in the guide - we're going to update to moodle 3.4 later in the month,  there are some different defaults or configurations that aren't working. Also, it could be that there's something about my user account that's an issue - e.g., being a lecturer rather than a student account, or similar. 

I'll have another look tomorrow morning, but if you have access to the logs and can see anything obvious in the requests you've been getting from City moodle, then let me know.

**Comment by iteles** [comment]
@stianr Might also be worth having a quick screenshare with @Danwhy at some point tomorrow (Monday) morning if you're available if you haven't sussed this out after your initial review.

**Comment by Danwhy** [comment]
Hi @stianr, the main reason I can think of for seeing that error would be that the secret is not set/correct. Did you get the email I sent with the secret token in?

**Comment by stianr** [comment]
Hi @Danwhy, I did that - copied and pasted the code and checked it had 10 chars in case copying had picked up extra spaces.

**Comment by Danwhy** [comment]
Ok @stianr, it looks like the problem is due to heroku using https, which will require a little more configuration on our lti side to get it to work. I'll let you know when I think I've got it working so you can try again

**Comment by stianr** [comment]
Thanks @Danwhy - let me know when you want me to test anything.

**Comment by Danwhy** [comment]
@stianr Could you try again now? You shouldn't need to change any of the configuration, just try to access Quodl through the link again

**Comment by stianr** [comment]
@Danwhy - I'm in! Will test now and get back to you in this thread.

**Comment by stianr** [comment]
First comments:
- It's cool!
- It's correctly sending lecturers and students to different URLs to sign up (I've tried with both account types).
- It's asking for email address when signing up. I'd hoped we'd be able to get the user's email address via LTI, so that (a) they didn't use a random gmail address, and (b) we didn't get loads of students putting in the wrong email address, as we get currently. Having tested further it looks like the email address is being passed from moodle, but when I tried it, the email field did not autofill with the email address from moodle. Would be ideal to have the email address filled and uneditable when the user arrives on the Quodl signup page.
- If the user enters an existing email address, then they get the 'user exists' error rather than merging with existing account. Maybe this doesn't happen if they use the email address passed from moodle?

Have a meeting now, but will test further in an hour or so. Great work!

**Comment by stianr** [comment]
- Once account is created, now seamlessly logs in to Quodl for student - very nice.
- For lecturer (possibly because of user exists issue earlier), clicking through now give a 404 error:

![image](https://user-images.githubusercontent.com/16817089/42446581-b9627fba-836e-11e8-94ad-e9300ad93a3b.png)

**Comment by stianr** [comment]
- If I click on the link in moodle as a student, enter Quodl, log out and close the Quodl tab, then click on the link again, I get sent to the login page, rather than the module page. If I close the Quodl tab and click through again, I'm logged in again - so not sure whether it's checking the login status before login is complete or something... We want to avoid students seeing the login page, as they're likely to start creating extra accounts.

**Comment by stianr** [comment]
- One attempt to click through as a (new, different) student gave a blank page, but the next time I tried it as the same student it went straight through to the module overview page - so I'm not sure what would have happened in that situation with the student's nickname.

**Comment by stianr** [comment]
@Danwhy I think the current priority is to ensure that when any user clicks through from moodle to Quodl, they get to a page with their email address pre-filled (and possibly uneditable), and which requires them to enter a nickname before proceeding. 

Happy to talk sometime this afternoon if it would help...

**Comment by Danwhy** [comment]
@stianr Hopefully the issues you mentioned have been resolved, if you'd like to give it another try and let us know if there's anything else

**Comment by stianr** [comment]
Thanks @Danwhy - would you be able to delete the accounts for StudentBadge1@city.ac.uk, StudentBadge2@city.ac.uk, and StudentBadge3@city.ac.uk, and for my email address as well? Then I can try signing up again from scratch.

**Comment by Danwhy** [comment]
@stian 👍 Done

**Comment by stianr** [comment]
Signing up as lecturer - email address is uneditable, which is nice, but no email address visible - tried both Chrome and Firefox:

![image](https://user-images.githubusercontent.com/16817089/42459530-b79b6a0a-8393-11e8-912b-991a8ffcd6d4.png)

Register button doesn't work, presumably because email address is empty?

**Comment by stianr** [comment]
Works perfectly as student:

![image](https://user-images.githubusercontent.com/16817089/42459749-3cdcf4f4-8394-11e8-8fc1-1e6dfcee2097.png)

**Comment by Danwhy** [comment]
Strange, but it could be to do with the name of the email field coming from your Moodle version. I'll put a log in and get you to try again if that's ok

**Comment by stianr** [comment]
Sure - let me know when to have another go.

**Comment by Danwhy** [comment]
I think I spotted the problem, should be fixed now

**Comment by stianr** [comment]
Fixed!

**Comment by stianr** [comment]
Different question: What happens with students who have already signed up with Quodl using their university email addresses. I registered as a student direct with Quodl first, then clicked through from moodle with the same email. It let me set up a separate account (studentbadge2@city.ac.uk). So there may be two instances of users with that single email address, which we'd ideally like to avoid. If I do it the other way round, set up an account via moodle, then try to register direct on Quodl with the same email, it tells me something went wrong and won't let me set up a second account.

For this PoC, it would be ideal if, when a user clicks through from moodle and is identified as not having clicked through from moodle before, a check is made for an existing user with the same email address. If the email address is found, it then keeps all the existing user details - quizzes completed, etc - but changes the account type to a moodle rather than password based one, and then the module that is associated with the moodle link that was just clicked is added to the student's dashboard. Is that feasible?

**Comment by Danwhy** [comment]
@stianr That should be what already happens. I've checked the database and there are two users with the same email address, but they have different casing (StudentBadge2@city.ac.uk vs studentbadge2@city.ac.uk).
I will make sure to downcase the email on signup, but if you could do the same test with the exact same email addresses in the meantime, it would be good to see if it works.

**Comment by stianr** [comment]
That's great - could you delete the accounts for both of those versions of that email address and I'll have another go.

**Comment by Danwhy** [comment]
@stianr Deleted the accounts, and fixed it so the capitalisation shouldn't be an issue now

**Comment by stianr** [comment]
Think this may be having knock-on effects. I tried signing up direct with Quodl, then clicked through from moodle, but didn't click to merge accounts (though that seemed to be working) - then remembered I hadn't added any modules, so went back and tried to log in direct with Quodl, and was told my institutional subscription had expired - as far as I'm aware, students should never see this:

![image](https://user-images.githubusercontent.com/16817089/42461761-2a56f3fc-8399-11e8-92e4-11820debe207.png)

**Comment by Danwhy** [comment]
It looks like studentbadge2@city.ac.uk is signed up as a lecturer, either through Quodl or Moodle. I'll look into what's happened

**Comment by Danwhy** [comment]
@stianr I think some of the problems were caused by the session information in the cookie being stored and so not matching when you logged in as two different users through Moodle.
That should be fixed now, but if you do have any trouble in testing again, could you take that into account and try using different browsers/incognito mode.

**Comment by stianr** [comment]
Thanks @Danwhy - I've been mainly using incognito mode for doing this, but may not have done so all the time. Will do it consistently when testing now.

**Comment by stianr** [comment]
All seems to be working - I've tried:

- registering on the site, then clicking through on moodle but not entering email address
- registering on the site, then clicking through on moodle but entering incorrect password

In both cases I could still log in via the site in the usual way, so the problem above seems fixed. Once I entered the correct password, the accounts seemed to be merged.
