### ISSUE TITLE
Restoring a user's session

### ISSUE THREAD

**Issue by minaorangina** [cul-2016/quiz#74]
#111
### Live quiz
If a student's page refreshes, how do we get them back on track?
* `quiz_id` is carried in the nextQuestion.  Currently unused
* `isQuizStarted` would be flipped back to false.  How to handle?

**Comment by minaorangina** [comment]
Generally need to make better use of browser storage solutions, like cookies and local storage

**Comment by minaorangina** [comment]
- [ ] create endpoint that loads a "loading" view
- [ ] behind the scenes, fetch user details
- [ ] once user details is stored in the state, redirect back to previous url

**Comment by sohilpandya** [comment]
** come across an issue where the onEnter functions are still running even though we want it to stop after the first function**

Ideally If the userState does not exist, we want them to redirect to app-loading component, and then continue to the page they were on prior to app-loading.

**Comment by sohilpandya** [comment]
**Current Implementation**

When the State from userstorage disappears and the user refreshes a page:
- they will be redirected to appLoading component
- we will store the current location in the localstorage
- once the user information has been fetched, we can redirect the user to the previous page using the path stored in localstorage

**Comment by sohilpandya** [comment]
**composeHooks**
The function has been changed:
- The callback takes a boolean as an argument
- if you pass `false` it will break out of it and it will not call anymore hooks

**Running Authenticate Hook**
- We wanted the function to stop running if user_id was undefined in the state
- instead it was continuing through to the next hook, which expected user_id to be defined and breaking the app (/module_id/lecturer). 
- We edited the composeHooks so that callback could take a boolean value and if it was passed false then it will stop the hook.
